sudo: required
dist: xenial
language: c
compiler: clang
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - sourceline: 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu xenial main'
    packages:
    # install toolchains
    - clang-3.8
    - cmake
branches:
  except:
    - legacy
    - experimental
git:
  depth: 3
before_install:
  - sudo apt-get update -qq
script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j4
  - ctest
  - ./tsc_test
matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

