sudo: required
dist: xenial
language: c
compiler: clang
group: stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - sourceline: 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu xenial main'
    packages:
    - clang-3.8
    - cmake
branches:
  except:
    - legacy
    - experimental
git:
  depth: 3
before_install:
  - bash ./.travis/install.sh
script:
  - bash ./.travis/build.sh
  - ctest
  - ./tsc_test
matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8

